In [1]:
# 1
import pandas as pd

In [2]:
# 2
df = pd.read_csv(r"C:\Users\Admin\.vscode\csv\pandas_practice.csv")

In [3]:
# 3
df.tail()

,Student_ID,Student_Name,Age,Class,Subject,Gender,Score,Attendance_Percent,Study_Hours
198,199,Mary,14,SS1B,Mathematics,Female,39.0,83.0,3.2
199,200,Joseph,13,SS1C,Biology,Female,95.0,81.0,1.4
200,36,Daniel,15,SS1D,Biology,Male,36.0,94.0,7.8
201,92,Ruth,13,SS1B,English,Female,45.0,80.0,2.3
202,151,John,16,SS1A,Computer Science,Female,51.0,100.0,1.7

In [4]:
# 4
print(df.shape)

(203, 9)

In [5]:
# 5
print(df.columns)

Index(['Student_ID', 'Student_Name', 'Age', 'Class', 'Subject', 'Gender',
       'Score', 'Attendance_Percent', 'Study_Hours'],
      dtype='str')

In [6]:
# 6
print(df.dtypes)
df.describe()

Student_ID              int64
Student_Name              str
Age                     int64
Class                     str
Subject                   str
Gender                    str
Score                 float64
Attendance_Percent    float64
Study_Hours           float64
dtype: object

       Student_ID         Age       Score  Attendance_Percent  Study_Hours
count  203.000000  203.000000  199.000000          199.000000   203.000000
mean   100.502463   14.862069   64.874372           83.552764     6.492118
std     57.916496    1.469387   18.945677           10.014937     3.116697
min      1.000000   13.000000   35.000000           65.000000     1.000000
25%     50.500000   13.000000   48.000000           74.000000     3.850000
50%    100.000000   15.000000   64.000000           84.000000     6.500000
75%    150.500000   16.000000   80.000000           92.000000     9.150000
max    202.000000   17.000000   98.000000          100.000000    11.900000

In [7]:
# 7
print(df.isnull().sum())

Student_ID            0
Student_Name          0
Age                   0
Class                 0
Subject               0
Gender                0
Score                 4
Attendance_Percent    4
Study_Hours           0
dtype: int64

In [8]:
# 8
print(df.duplicated().sum())

3

In [9]:
# 9
print(df.drop_duplicates())

     Student_ID Student_Name  Age Class           Subject  Gender  Score  \
0             1        Peter   13  SS1C           English    Male   52.0
1             2      Deborah   13  SS1D       Mathematics    Male   46.0
2             3        Sarah   13  SS1B  Computer Science  Female   63.0
3             4       Samuel   14  SS1D           Biology  Female   54.0
4             5     Benjamin   13  SS1A         Chemistry    Male   80.0
..          ...          ...  ...   ...               ...     ...    ...
195         196         Paul   13  SS1A         Chemistry  Female   40.0
196         197       Joshua   13  SS1C       Mathematics  Female   65.0
197         198     Benjamin   14  SS1A           Biology  Female   57.0
198         199         Mary   14  SS1B       Mathematics  Female   39.0
199         200       Joseph   13  SS1C           Biology  Female   95.0

     Attendance_Percent  Study_Hours
0                  71.0          8.4
1                  78.0          3.6
2                  93.0          7.5
3                  78.0         11.5
4                  87.0          7.6
..                  ...          ...
195                89.0         11.8
196                71.0          9.5
197                94.0         11.8
198                83.0          3.2
199                81.0          1.4

[200 rows x 9 columns]

In [10]:
# 10
df.Student_Name = df.Student_Name.str.strip().str.title().str.replace(" ", "_")
print(df.Student_Name)

0         Peter
1       Deborah
2         Sarah
3        Samuel
4      Benjamin
         ...
198        Mary
199      Joseph
200      Daniel
201        Ruth
202        John
Name: Student_Name, Length: 203, dtype: str

In [11]:
# 11
print(df.dtypes)

Student_ID              int64
Student_Name              str
Age                     int64
Class                     str
Subject                   str
Gender                    str
Score                 float64
Attendance_Percent    float64
Study_Hours           float64
dtype: object

In [12]:
# 12
print(df.isna().sum())

Student_ID            0
Student_Name          0
Age                   0
Class                 0
Subject               0
Gender                0
Score                 4
Attendance_Percent    4
Study_Hours           0
dtype: int64

In [13]:
# 13
print(df["Score"].mean())

64.87437185929649

In [14]:
# 14
print(df["Score"].max())

98.0

In [15]:
# 15
print(df["Score"].min())

35.0

In [16]:
# 16
print(df.drop_duplicates())
print(df.count())

     Student_ID Student_Name  Age Class           Subject  Gender  Score  \
0             1        Peter   13  SS1C           English    Male   52.0
1             2      Deborah   13  SS1D       Mathematics    Male   46.0
2             3        Sarah   13  SS1B  Computer Science  Female   63.0
3             4       Samuel   14  SS1D           Biology  Female   54.0
4             5     Benjamin   13  SS1A         Chemistry    Male   80.0
..          ...          ...  ...   ...               ...     ...    ...
195         196         Paul   13  SS1A         Chemistry  Female   40.0
196         197       Joshua   13  SS1C       Mathematics  Female   65.0
197         198     Benjamin   14  SS1A           Biology  Female   57.0
198         199         Mary   14  SS1B       Mathematics  Female   39.0
199         200       Joseph   13  SS1C           Biology  Female   95.0

     Attendance_Percent  Study_Hours
0                  71.0          8.4
1                  78.0          3.6
2                  93.0          7.5
3                  78.0         11.5
4                  87.0          7.6
..                  ...          ...
195                89.0         11.8
196                71.0          9.5
197                94.0         11.8
198                83.0          3.2
199                81.0          1.4

[200 rows x 9 columns]
Student_ID            203
Student_Name          203
Age                   203
Class                 203
Subject               203
Gender                203
Score                 199
Attendance_Percent    199
Study_Hours           203
dtype: int64

In [17]:
# 17
print(df["Attendance_Percent"].mean())

83.55276381909547

In [18]:
# 18
print(df["Study_Hours"].mean())

6.492118226600986

In [19]:
# 19
print(df.groupby("Class")["Score"].mean())

Class
SS1A    65.065217
SS1B    64.500000
SS1C    65.632653
SS1D    64.354167
Name: Score, dtype: float64

In [20]:
# 20
print(df.groupby("Class")["Score"].max())

Class
SS1A    98.0
SS1B    97.0
SS1C    97.0
SS1D    98.0
Name: Score, dtype: float64

In [21]:
# 21
print(df.groupby("Class")["Score"].min())

Class
SS1A    37.0
SS1B    35.0
SS1C    39.0
SS1D    36.0
Name: Score, dtype: float64

In [22]:
# 22
total = df["Student_ID"].count()
print(df.groupby("Class")["Student_ID"].count())

Class
SS1A    47
SS1B    59
SS1C    49
SS1D    48
Name: Student_ID, dtype: int64

In [23]:
# 23
print(df.groupby("Subject")["Score"].mean())

Subject
Biology             67.450000
Chemistry           66.022727
Computer Science    63.685714
English             62.714286
Mathematics         60.212121
Physics             70.263158
Name: Score, dtype: float64

In [24]:
# 24
print(df.groupby("Class")["Attendance_Percent"].mean())

Class
SS1A    84.297872
SS1B    84.142857
SS1C    83.551020
SS1D    82.106383
Name: Attendance_Percent, dtype: float64

In [25]:
# 25
print(df.groupby("Class")["Score"].mean().max())

65.63265306122449

In [26]:
# 26
print(df.groupby("Subject")["Score"].mean().max())

70.26315789473684

In [27]:
# 27
print(df.groupby("Class")["Attendance_Percent"].mean().max())

84.29787234042553

In [28]:
# 28
df["Passed"] = df["Score"] >= 50

In [29]:
# 29
passed = df["Passed"].sum()
print(passed)

141

In [30]:
# 30
passed_percent = (passed/total) * 100
print(f"{passed_percent}%")

69.45812807881774%

In [ ]:
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